### ISSUE TITLE
Custom Model without extends BaseModel

### ISSUE THREAD

**Issue by popovserhii** [goldcaddy77/warthog#103]
Is it possible to create a simple model without fields which are presented in `BaseModel` except `ID` field?

Here is my model:
```typescript
import { Column, PrimaryGeneratedColumn } from 'typeorm';
import { Field, ID, ObjectType } from 'type-graphql';
import { Model, IDType, StringField } from 'warthog';

@Model()
@ObjectType()
export class Role {
  @Field(type => ID)
  @PrimaryGeneratedColumn({ type: "integer" })
  id!: IDType;

  @StringField()
  @Column({ nullable: false })
  mnemo?: string;
}
```
When I try to run `yarn generate:code` it returns error:
```
$ yarn generate:code
yarn run v1.15.2
$ set NODE_ENV=development && dotenv -- ts-node tools/generate.ts
Error: Schema must contain uniquely named types but contains multiple types named "Role".
    at invariant (D:\WebServer\git\selection-warthog\packages\warthog-examples\node_modules\graphql\jsutils\invariant.js:19:11)
    at typeMapReducer (D:\WebServer\git\selection-warthog\packages\warthog-examples\node_modules\graphql\type\schema.js:298:57)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (D:\WebServer\git\selection-warthog\packages\warthog-examples\node_modules\graphql\type\schema.js:145:28)
    at Function.generateFromMetadataSync (D:\WebServer\git\selection-warthog\packages\warthog-examples\node_modules\type-graphql\schema\schema-generator.js:28:24)
    at Function.<anonymous> (D:\WebServer\git\selection-warthog\packages\warthog-examples\node_modules\type-graphql\schema\schema-generator.js:15:33)
    at Generator.next (<anonymous>)
    at D:\WebServer\git\selection-warthog\packages\warthog-examples\node_modules\tslib\tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\WebServer\git\selection-warthog\packages\warthog-examples\node_modules\tslib\tslib.js:103:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

Am I doing something wrong?

**Comment by goldcaddy77** [comment]
Hey, can you create a branch that reproduces this and I'll take a look?

**Comment by popovserhii** [comment]
Yes, of course. Please, check at this [branch](https://github.com/popovserhii/warthog-examples/tree/simple-model)

**Comment by popovserhii** [comment]
> Also can you elaborate on what you're trying to do that is outside of the base behaviour?

There are many cases where we do not need to have all of these fields in Model, such as `deletedAt`, `updatedById`, `createdAt`, `createdById` etc. 
I'd like to have my models as simple as possible without redundant fields.

**Comment by goldcaddy77** [comment]
Gotcha, so this would actually require a library update, which I can make this week. Once the change is in place you'd just need to create your own version of BaseModel like I do here with whatever options you want:

https://github.com/goldcaddy77/warthog/blob/master/src/core/BaseModel.ts

You could also just use both the TypeORM and TypeGraphQL decorators on each class you create, but that gets verbose quickly.

**Comment by goldcaddy77** [comment]
Looking at your error message again you're doubling up on decorators: 

```
@Model()
@ObjectType()
export class Role {
```

When you use Warthog's @Model it already adds an ObjectType decorator:

https://github.com/goldcaddy77/warthog/blob/master/src/decorators/Model.ts#L28

Same with all of the field decorators:

https://github.com/goldcaddy77/warthog/blob/master/src/decorators/StringField.ts#L26

Check out the examples folder for a good starting point:

https://github.com/goldcaddy77/warthog/tree/master/examples

**Comment by popovserhii** [comment]
@goldcaddy77, you are right, the problem was with redundant `@ObjectType()` decorator.
But now, when I try to create `RoleResolver` it requires `BaseModel` again. Is there any workaround about it?

![image](https://user-images.githubusercontent.com/1991183/58377685-d2c94480-7f8e-11e9-87ba-069d234ece94.png)

**Comment by goldcaddy77** [comment]
@popovserhii - sorry for slow response.  I'm not sure why that's happening.  Can you reproduce somewhere and shoot me a link?  A few ideas:

1. Try tweaking your tsconfig settings
2. Instead of using BaseResolver, you can try to instead use a vanilla resolver and instead call into BaseService like so:

- https://github.com/goldcaddy77/warthog/blob/master/examples/6-base-service/src/user.resolver.ts
- https://github.com/goldcaddy77/warthog/blob/b973ab0ca0118b1aed5fcbcb5a8b57793174e254/examples/7-feature-flags/src/environment/environment.resolver.ts#L26

**Comment by popovserhii** [comment]
The same problem with `Service`. It requires that all [`Model extends BaseModel`](https://github.com/goldcaddy77/warthog/blob/master/src/core/BaseService.ts#L10). Really we cannot even use `BaseModelUUID` because `BaseModel` should be always presented in the code.

We should simplify `BaseModel` and leave only `id` field or allow to developer personally decide which type pass to `Service`. Something like this `export class BaseService<E>` or `export class BaseService<E | E extends BaseModel>` can be declared in [`BaseService`](https://github.com/goldcaddy77/warthog/blob/master/src/core/BaseService.ts#L10)

**Comment by goldcaddy77** [comment]
Gotcha, makes sense. So it sounds like you just don't want the version, timestamps and attribution columns right? If I update the library so that it doesn't break if you don't use BaseModel, would your use case be covered?

**Comment by popovserhii** [comment]
Exactly, I just don't need a version, timestamp and other default columns in Model. And yes, if you can do this my use case will be covered.

**Comment by goldcaddy77** [comment]
@popovserhii I took a stab at what you were asking for here: https://github.com/goldcaddy77/warthog/pull/152/files#diff-325440f1fb60c7c5716bc13d6e8e4dffR90

Let me know what you think.  What were you thinking to use for IDs?  Also, since there is a stong assumption that we use soft deletes, you'll minimally need the `deletedAt` field.

**Comment by goldcaddy77** [comment]
@popovserhii - what do you think of ^^^?

**Comment by popovserhii** [comment]
@goldcaddy77, sorry for a long delay.
It is what I need. Only one question, why do we need `deletedAt` field in `MinimalModel`? I understand that **_soft deletes_** is appropriate in most cases but sometimes we really need **_hard delete_** from a database.

I have one project where data is collecting for history every half hour and during the day the number of new rows increases up to ~432000, this data is actual only for 3 months then they should be deleted from DB entirely. That why not always we can follow the **_soft delete_** strategy.

> What were you thinking to use for IDs?

I use `int` for IDs.

I'll try new `MinimalModle` implementation in next week.

**Comment by John0x** [comment]
I agree that soft deletes should be optional. There are a lot of cases where a hard delete is necessary, especially with the whole privacy stuff

**Comment by goldcaddy77** [comment]
@John0x - makes sense. It would take a bit to implement this feature in an elegant way.  There is no reason why you couldn’t hard delete as it stands. I could add a `hardDelete` method to BaseService to help in the meantime.

**Comment by goldcaddy77** [comment]
@popovserhii just wanted to let you know that this works in Warthog V3 Beta.  I'll release V3 in October, but you can start playing with it now with `yarn add warthog@beta`
