### ISSUE TITLE
Example for how to generate migrations

### ISSUE THREAD

**Issue by goldcaddy77** [goldcaddy77/warthog#12]
See https://github.com/typeorm/typeorm/blob/master/docs/migrations.md

**Comment by bdombro** [comment]
I created an example --> https://github.com/bdombro/warthog-migration-example

@goldcaddy77 maybe add a link to it in the warthog README.md?

**Comment by goldcaddy77** [comment]
Sweet thanks. This should be part of this project's documentation, though... Probably another section in the README under https://github.com/goldcaddy77/warthog/blob/master/README.md#4-run-your-server . Maybe section 5. "Generate Migrations"?

**Comment by bdombro** [comment]
Update: My example is now fully working and functional!

**Comment by goldcaddy77** [comment]
Closing.  I have a big README update coming.
