### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by goldcaddy77** [goldcaddy77/warthog#13]
Really need to add tests before folks should start consuming

**Comment by overpod** [comment]
no tests !!! No production.
great idea for a product

**Comment by goldcaddy77** [comment]
Yeah, I hear you.  I'm going to beef up the test suite over the next month or so as the API solidifies.  Thanks for checking out my project!

**Comment by goldcaddy77** [comment]
@overpod - test coverage up to 79%.  See https://github.com/goldcaddy77/warthog/pull/163 - more coming.

**Comment by goldcaddy77** [comment]
Closing this as test coverage is now over 87%:  https://codecov.io/gh/goldcaddy77/warthog/commits

**Comment by overpod** [comment]
This is a great job. I think to try the product on the pet project.

**Comment by overpod** [comment]
Must close the issue.
