### ISSUE TITLE
Postgres timestamp field (intentionally?) unsupported?

### ISSUE THREAD

**Issue by IniZio** [goldcaddy77/warthog#190]
https://github.com/goldcaddy77/warthog/blob/ef79436357bacc32deec1f02f40f21e051bd0860/src/schema/TypeORMConverter.ts#L94

Here the 'timestamp' type is ignored, which causes 
```
Error: convertToGraphQLType: Unexpected type: timestamp
```

when I use `DateField`

Not sure why it is commented out though?

**Comment by goldcaddy77** [comment]
Good catch. Will fix right away.

**Comment by IniZio** [comment]
Also not sure if primitive arrays are supported? :thinking:

**Comment by goldcaddy77** [comment]
Primitive arrays should work. Why do you think they might not?

**Comment by goldcaddy77** [comment]
@IniZio : https://github.com/goldcaddy77/warthog/pull/191 to fix `timestamp`.   Please open a new issue if you find something with primitive arrays
