### ISSUE TITLE
No support for primitive array

### ISSUE THREAD

**Issue by IniZio** [goldcaddy77/warthog#193]
Mentioned in #190 , there is no primitive array decorator in https://github.com/goldcaddy77/warthog/tree/master/src/decorators.

Now if i use the normal typeorm + type-graphql way i.e.
```js
@Column({type: 'text', array: true, nullable: true })
@Field(() => [String], {nullable: true})
decorations?: string[]
```

it will obviously not work because they do not have the meta and will get parsed into string, causing type error

**Comment by goldcaddy77** [comment]
Good catch.  How would you expect this to work?

- Sorting: likely doesn't make sense
- Filtering: what operators should be supported?  Perhaps just `contains`?

Do you know if TypeORM/Postgres have the operators to cleanly filter in array columns?

**Comment by IniZio** [comment]
Yes that is what I was concerned too because will need to generate a raw query for each kind of database.

Before i tried warthog, I set array field in models like
```js
@Field(type => [String], { nullable: true })
@Column({ type: 'text', array: true, nullable: true })
hobbies?: string[];
```

and then use filter like
```js
      usersQuery = usersQuery.andWhere(
        'users.hobbies && ARRAY[:...hobbies]::text[]',
        { hobbies }
      );
```

I think will need to generate raw queries like this?

**Comment by goldcaddy77** [comment]
To make this work with how I'm currently doing things in Warthog we'll likely need to make use of the `Raw` operator here:

https://github.com/typeorm/typeorm/blob/master/docs/find-options.md

...and have it map to Postgres`s array search operator:

```
select * from people where aliases @> '{"Prince Harry"}';
```

See: https://www.fulcrumapp.com/blog/tips-postgresql-arrays/

**Comment by IniZio** [comment]
Will see if I have time for to create a PR :)

**Comment by goldcaddy77** [comment]
@BenBrostoff should be easier now that I’ve refactored the codegen pipeline. Will touched a lot of different spots, through. Lemme know if you gets need this.

**Comment by goldcaddy77** [comment]
@BenBrostoff do you guys still need this?

**Comment by IniZio** [comment]
Actually no for me now since array is not performant for querying 🤔

**Comment by BenBrostoff** [comment]
@goldcaddy77 I think we should be fine for now 👍
