### ISSUE TITLE
@ArgsType composite objects missing prototype information for child objects

### ISSUE THREAD

**Issue by deweyjose** [goldcaddy77/warthog#24]
https://github.com/goldcaddy77/warthog/blob/54424fba7a1989d4607353debf0282ef5d9712eb/examples/1-simple-model/src/user.resolver.ts#L39

There will be missing prototype information on the 'data' and 'where' objects. Downstream code in typeorm called from BaseResolver.ts depends on prototype information. Decisions for query generation are made by statements that call instanceof Object, which evaluate to false since prototype information is missing.

One workaround is to change the function signature such that each child object becomes a parameter:

 @Arg('data') data: UserUpdateInput,
@Arg('where') where: UserWhereUniqueInput,

**Comment by goldcaddy77** [comment]
@deweyjose could we get around this be coverting the plain object to an instance of the class using [
https://github.com/goldcaddy77/warthog/blob/master/src/utils/EntityCreator.ts#L4](EntityCreator)?

**Comment by goldcaddy77** [comment]
This will be fixed in Warthog V3, closing.
