### ISSUE TITLE
How to support multiple databases

### ISSUE THREAD

**Issue by JeniTurtle** [goldcaddy77/warthog#273]
How to support multiple databases

**Comment by goldcaddy77** [comment]
Hi @JeniTurtle , I’m not currently supporting multiple databases so that I can check all of the boxes for Postgres first. What database do you want to use?

**Comment by JeniTurtle** [comment]
I like postgres！

**Comment by goldcaddy77** [comment]
Cool, then you’re all set!

**Comment by goldcaddy77** [comment]
Closing as dupe of https://github.com/goldcaddy77/warthog/issues/96
