### ISSUE TITLE
Decouple schema and code generation from App 

### ISSUE THREAD

**Issue by deweyjose** [goldcaddy77/warthog#28]
May need to refactor and decouple the schema generators from App startup. Perhaps a Generator class that manage the generated code. This way we can generate code during the build process without needing a database running, which is required right now when the App object is instantiated.

**Comment by goldcaddy77** [comment]
Good idea - will give this a whirl this weekend.

**Comment by goldcaddy77** [comment]
Addressed in https://github.com/goldcaddy77/warthog/pull/43/files

**Comment by goldcaddy77** [comment]
You actually need a database to generated the code right now as I piggyback on the TypeORM metadata, but I found a workaround where we can just use a sqlite connection, which we should be able to establish pretty cheap in any environment, including CI.

See https://github.com/goldcaddy77/warthog/blob/master/examples/2-complex-example/tools/generate.ts
