### ISSUE TITLE
python/postgres integration

### ISSUE THREAD

**Issue by bsdis** [goldcaddy77/warthog#293]
Hi, I have my backend running in python using django and postgress.
In Django, the datamodels and migrations and such are defined in python and then automatically the database schema is updated using the migrations.
I need to keep it that way - but I also need a consistent way to convert it all to GQL schemas etc.
So I want to ask if its possible to have warthog create alle the typescript schemas etc. by introspecting the postgress DDL?
I am hoping for a workflow where i define my models and associations in django, migrate it to database and then use warthog to generate my GQL schemas etc. automatically from the database - that way I only have to keep track of all my models in 1 place. Is that possible?

**Comment by goldcaddy77** [comment]
Hi @bsdis, taking Postgres and converting to GraphQL is not in the scope of Warthog. Warthog takes a schema in TypeScript and generates the everything. The [Postgraphile](https://www.graphile.org/postgraphile/) project might be able to give you what you’re looking for, though.
