### ISSUE TITLE
Can one do transactions with this?

### ISSUE THREAD

**Issue by bedeho** [goldcaddy77/warthog#317]
Warthog appears very suitable for a project I am focusing, however I need support for transactional mutation of the database when adding data to it programmatically (not through the GraphQL API). Is this possible, if so how?

**Comment by goldcaddy77** [comment]
See https://github.com/goldcaddy77/warthog/issues/94 .  This should be possible - need to determine how many tough points there would be porting to `TransactionRepository`

**Comment by goldcaddy77** [comment]
What kind of project are you kicking off?

**Comment by goldcaddy77** [comment]
Here are docs to how `typeorm` (and therefore Warthog) does Transactions: https://github.com/typeorm/typeorm/blob/master/docs/transactions.md#transaction-decorators

I'll work on getting an example in place.

**Comment by bedeho** [comment]
Thank you for the very fast response, really appreciate it.

We are building a query server for a blockchain project (https://github.com/Joystream/), and we are looking for a database/GraphQL API infrastructure that limits the amount of boilerplate we have to maintain. I have been trying out Prisma (1) the last week. Its OpenCrud API and generated CRUD ORM were excellent, but in the end, it is missing database transactions. They have some longstanding open issues on this, but they have not been tended to in a very long time, and in general, there is a great deal of uncertainty around Prisma 2 arrival and eventual transactional support. 

An example would be really wonderful because there are a lot of moving parts here, and I am new to just about all of them (TypeORM, TypeGraphQL, etc.).

Have you ever considered opening up a Gitter channel or something similar? It would make it even easier for people to get started, and third parties to help each other.

**Comment by goldcaddy77** [comment]
Very cool - yeah this sounds like a perfect use case for you. I do have a Gitter - you can find me here: https://gitter.im/warthog-graphql/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by goldcaddy77** [comment]
All set, see https://github.com/goldcaddy77/warthog/pull/319/files#diff-0ef73fed426f71bd2379b3f18e90243aR1 for first-class support in Warthog.  Note that you can always drop down to using TypeORM directly and use the tools here: https://github.com/typeorm/typeorm/blob/master/docs/transactions.md .  Note that you would need to do your own validations, though (something that BaseClass handles).

**Comment by bedeho** [comment]
Fantastic, I really appreciate it. Looking forward to trying this out, will let you know how it turns out.

**Comment by goldcaddy77** [comment]
Perfect, sounds good.

**Comment by goldcaddy77** [comment]
Fix merged and documentation added to README.
