### ISSUE TITLE
warthog db:create not respecting db settings in .env

### ISSUE THREAD

**Issue by davidsielert** [goldcaddy77/warthog#323]
```
$ C:\Users\david\projects\warthog\node_modules\.bin\warthog db:create
connect ECONNREFUSED 127.0.0.1:5432
Done in 3.18s.
```

I have added the settings in .env

**Comment by goldcaddy77** [comment]
Can you share your `.env`? (or a scrubbed version)

**Comment by dsielert** [comment]
```
DEBUG=*
NODE_ENV=development
WARTHOG_AUTO_OPEN_PLAYGROUND=false
WARTHOG_AUTO_GENERATE_FILES=false
WARTHOG_APP_HOST=localhost
WARTHOG_APP_PORT=4100
WARTHOG_DB_DATABASE=warthog
WARTHOG_DB_HOST=192.168.1.35
WARTHOG_DB_LOGGING=all
WARTHOG_DB_PASSWORD=warthog
WARTHOG_DB_PORT=5432
WARTHOG_DB_SYNCHRONIZE=true
WARTHOG_DB_USERNAME=warthog
```

**Comment by davidsielert** [comment]
```
DEBUG=*
NODE_ENV=development
WARTHOG_AUTO_OPEN_PLAYGROUND=false
WARTHOG_AUTO_GENERATE_FILES=false
WARTHOG_APP_HOST=localhost
WARTHOG_APP_PORT=4100
WARTHOG_DB_DATABASE=warthog
WARTHOG_DB_HOST=192.168.1.35
WARTHOG_DB_LOGGING=all
WARTHOG_DB_PASSWORD=warthog
WARTHOG_DB_PORT=5432
WARTHOG_DB_SYNCHRONIZE=true
WARTHOG_DB_USERNAME=warthog
```

**Comment by ERespaldiza** [comment]
Try adding also PGUSER to .env file
`
PGUSER=postgres
`

**Comment by goldcaddy77** [comment]
Thanks @ERespaldiza - I think you’re right. It’s looking at localhost, but not authenticating.

**Comment by goldcaddy77** [comment]
I’ll update the README to mention PGUSER

**Comment by davidsielert** [comment]
I'm not using localhost for postgres , its 192.168.1.35 .. Its not using the env setting for WARTHOG_DB_HOST

**Comment by goldcaddy77** [comment]
Ohhh misread that. In order to diagnose, I’d make sure you’re running the command from the project root, then add some log lines in the node_modules folder for warthog in this file https://github.com/goldcaddy77/warthog/blob/master/src/cli/commands/dbCreate.ts#L11 . I can’t see how the config module wouldn’t load that value.

**Comment by smoll** [comment]
I came across this issue when trying this project for the first time, and when I log it, it is seeing the values (I'm running the whole thing in docker compose):

```
    WARTHOG_DB_PORT: '5432',
    ...
    WARTHOG_APP_HOST: 'localhost',
    WARTHOG_APP_PORT: '4100',
    WARTHOG_DB_HOST: 'db',
    WARTHOG_DB_LOGGING: 'all',
    WARTHOG_DB_DATABASE: 'myuser',
    WARTHOG_DB_PASSWORD: 'mypassword',
    WARTHOG_DB_USERNAME: 'myuser'
```

I did some further digging and wonder if this may actually be the culprit: https://github.com/goldcaddy77/warthog/blob/177181d09e79c4b305dc4aa78d4c0b1911b77242/src/cli/extensions/db-extension.ts#L34

when I logged the return value of the first parameter, I got this:

```js
getPgConfig(config) retval====== Promise {
  { host: 'db', user: 'myuser', password: 'mypassword', port: '5432' }
}
```

`getPgConfig()` is an async function, but it isn't actually being awaited. I think it should either be awaited, or made a non-`async` function.

**Comment by goldcaddy77** [comment]
@smoll are you windows or Unix?

I can fix this over the weekend unless somebody wants to toss in a quick PR.

**Comment by goldcaddy77** [comment]
I’m surprised this wasn’t caught by eslint: https://github.com/goldcaddy77/warthog/blob/master/.eslintrc.js#L39

**Comment by smoll** [comment]
@goldcaddy77 I am running this in a linux container and my host OS is ubuntu (not sure if that matters). In any event, I created a PR for the code change, which fixed the issue for me: https://github.com/goldcaddy77/warthog/pull/324

**Comment by dsielert** [comment]
while above I ran it in windows I get the same result on my mac
