### ISSUE TITLE
apiOnly field option does not work

### ISSUE THREAD

**Issue by diegonc** [goldcaddy77/warthog#332]
Setting the apiOnly option to a field of a model throws the following error:

```
src/modules/person/person.model.ts(11,17): error TS2345: Argument of type '{ apiOnly: boolean; }' is not assignable to parameter of type 'StringFieldOptions'.
  Object literal may only specify known properties, and 'apiOnly' does not exist in type 'StringFieldOptions'.
src/modules/person/person.model.ts(14,17): error TS2345: Argument of type '{ apiOnly: boolean; }' is not assignable to parameter of type 'StringFieldOptions'.
  Object literal may only specify known properties, and 'apiOnly' does not exist in type 'StringFieldOptions'.
```
It seems that the type StringFieldOption doesn't have the property apiOnly that is documented in the readme file.

Is there anything I can do to workaround this error or fix it?

-----

Environment
```
$ node_modules/.bin/warthog --version
1.51.1
$ yarn --version
1.22.4
$ node --version
v10.15.2
```

**Comment by diegonc** [comment]
OK I think I fixed it, at least partially. I found in the old readme that for my version of warthog the type-graphql decorators should be used.

So after 
```
import { Field } from 'type-graphql';
```
my model class
```
@Model()
export class Person extends BaseModel {
  @StringField()
  firstName!: string;

  @StringField()
  lastName!: string;

  @Field(type => String)
  email!: string;

  @Field(type => String)
  password!: string;

  @StringField()
  userId: string = '';
}
```
generates the following SDL
```
type Person implements BaseGraphQLObject {
  id: ID!
  createdAt: DateTime!
  createdById: String!
  updatedAt: DateTime
  updatedById: String
  deletedAt: DateTime
  deletedById: String
  version: Int!
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  userId: String!
}

input PersonCreateInput {
  firstName: String!
  lastName: String!
  userId: ID!
}
```
However, as you can see in the `PersonCreateInut` the API only fields are missing. I'd rather get them defined in the input type and let the resolver decide which ones to use for the database and which ones will get forwarded somewhere else.

**Comment by goldcaddy77** [comment]
@diegonc what version are you on? That option was added recently. Please try bumping to latest and see if you still get the error.

**Comment by diegonc** [comment]
Is there anything I should do to get the newer version? `yarn add warthog` installed that old version

**Comment by goldcaddy77** [comment]
`yarn add warthog@latest`

**Comment by diegonc** [comment]
Thanks! It's working now. I also had to change the version in `package.json` after `yarn warthog new`

**Comment by goldcaddy77** [comment]
Awesome, glad it's working.  I'll put in a PR to update the `new` command.

**Comment by goldcaddy77** [comment]
`new` has been updated: https://github.com/goldcaddy77/warthog/pull/336
