### ISSUE TITLE
Any particular reason for node 12.x only?

### ISSUE THREAD

**Issue by GrayStrider** [goldcaddy77/warthog#334]
One of my packages is 13.2 + and now I'll have to mess around with nvm or whatnot. Just curious.

**Comment by goldcaddy77** [comment]
This is just an issue with `warthog-starter`.  Warthog will work with Node 8+.  I just put in a PR to `warthog-starter` to fix this:  https://github.com/goldcaddy77/warthog-starter/pull/43

**Comment by goldcaddy77** [comment]
Thanks for calling this out 👍
