### ISSUE TITLE
Having troubles starting warthog-starter on Windows

### ISSUE THREAD

**Issue by GrayStrider** [goldcaddy77/warthog#335]
```
$ dotenvi -s ${WARTHOG_ENV:-development}
Could not load yaml Error: Could not locate stage ${WARTHOG_ENV:-development} in file env.yml
```

Or when starting `start:dev:watch`
![image](https://user-images.githubusercontent.com/43771776/78733650-c628c180-7991-11ea-801f-b8698f80eb95.png)

Any ideas what might cause this?

**Comment by goldcaddy77** [comment]
What happens if you run `yarn dotenv:generate`?

**Comment by goldcaddy77** [comment]
If you're running `dotenvi -s ${WARTHOG_ENV:-development}` my guess is that it's not interpolating `${WARTHOG_ENV:-development}` into `development` so it's getting stuck.  Do you know if `yarn` on windows supports that syntax?  I would assume so...

**Comment by goldcaddy77** [comment]
Also, for `warthog-starter` issues, you should keep all of those in that repo.  Can we move this discussion over there?

**Comment by GrayStrider** [comment]
I'll try all of the above and ask further questions in `warthog-starter`, thanks.
