### ISSUE TITLE
Allow option to conform to Relay spec

### ISSUE THREAD

**Issue by goldcaddy77** [goldcaddy77/warthog#338]
* https://relay.dev/graphql/connections.htm
* https://graphql.org/learn/pagination/

**Comment by goldcaddy77** [comment]
@FOSSforlife  Making good progress here: https://github.com/goldcaddy77/warthog/pull/340

**Comment by bedeho** [comment]
Hi, what is the status on this? Is there anything we can do to help advance this along sooner, we would love to ship with this feature as part of an upcoming release.

**Comment by goldcaddy77** [comment]
Hey, I put this on hold to work on various items for [Warthog V3](https://github.com/goldcaddy77/warthog/milestone/1).  Will dust it off right now and see if I can push it through.

**Comment by bedeho** [comment]
Would mean the world to us, thank you so much, how could we keep up with that? Please let us know if you crack open a PR or something at some point.

**Comment by goldcaddy77** [comment]
I worked on it a bunch tonight... Still need to wire things up in BaseService. I can probably finish it up tomorrow night.

**Comment by bedeho** [comment]
Fantastic!

**Comment by goldcaddy77** [comment]
Did a bunch more work last night - getting close: https://github.com/goldcaddy77/warthog/pull/408. Just need one more push.

**Comment by goldcaddy77** [comment]
One more push got things very close: https://github.com/goldcaddy77/warthog/pull/408/commits .  You can start playing with it on branch  `issue-338-relay-spec` if you want.  I need more tests though before I want to merge it down.

**Comment by bedeho** [comment]
Great, will ask one of our guys to try using it asap and provide feedback.

**Comment by metmirr** [comment]
@goldcaddy77 I tried to play with it on that branch but I am getting errors. For example, I created a sample model named `User` and then I tried to run `warthog codegen` it failed with these errors:

```
src/modules/user/user.resolver.ts:26:30 - error TS2344: Type 'UserWhereInput' does not satisfy the constraint 'WhereInput'.
  Type 'UserWhereInput' is not assignable to type 'WhereExpression'.
    Index signature is missing in type 'UserWhereInput'.

26     return this.service.find<UserWhereInput>(where, orderBy, limit, offset, fields);
                                ~~~~~~~~~~~~~~
src/modules/user/user.resolver.ts:31:33 - error TS2558: Expected 0 type arguments, but got 1.

31     return this.service.findOne<UserWhereUniqueInput>(where);
                                   ~~~~~~~~~~~~~~~~~~~~
src/modules/user/user.resolver.ts:52:38 - error TS2345: Argument of type 'UserWhereUniqueInput' is not assignable to parameter of type 'WhereExpression'.
  Index signature is missing in type 'UserWhereUniqueInput'.

52     return this.service.update(data, where, userId);
```

Building and installing warthog:

1. Build warthog from  `issue-338-relay-spec` branch - `yarn build`
2. Install the version from step 1 - `yarn add /path/to/warthog.tgz`

**Comment by goldcaddy77** [comment]
I'm working on this now and plan on having this merged in the next few hours.

**Comment by goldcaddy77** [comment]
Merged: https://github.com/goldcaddy77/warthog/pull/408

Let me know if this works.  You can find usage here:

- https://github.com/goldcaddy77/warthog/blob/eeddc26e52a2ef18bd34fd727eb06a7d24f3ae59/src/core/BaseService.test.ts#L67
- https://github.com/goldcaddy77/warthog/blob/eeddc26e52a2ef18bd34fd727eb06a7d24f3ae59/src/test/modules/dish/dish.resolver.ts#L110-L116

**Comment by goldcaddy77** [comment]
@bedeho / @metmirr let me know how this works.  Currently porting it to V3 as well.

**Comment by bedeho** [comment]
Hopefully, @metmirr can get back to you by Monday ;)

**Comment by metmirr** [comment]
@goldcaddy77 by following the usage in the tests I was able to create a connection. Now my question is cli is not generating connection related `ObjectType`, `ArgType` etc. So do I need to define these types for every resolver that I have? For the `Dish` example you have defined `DishEdge`, `DishConnection`, `ConnectionPageInputOptions`, and `DishConnectionWhereArgs`

**Comment by goldcaddy77** [comment]
Hi, yes for now you do need to create those manually, but we can add an option to auto-generate them pretty easily.  Feel free to take a stab.  You'll just need to add the additional functions to https://github.com/goldcaddy77/warthog/blob/main/src/schema/TypeORMConverter.ts and call them in https://github.com/goldcaddy77/warthog/blob/main/src/schema/SchemaGenerator.ts

**Comment by goldcaddy77** [comment]
@metmirr going to track the auto-gen for Connection queries in https://github.com/goldcaddy77/warthog/issues/331, closing.
