### ISSUE TITLE
Composite unique index on relationship entity

### ISSUE THREAD

**Issue by diegonc** [goldcaddy77/warthog#343]
I have a relationship entity and want to generate a composite index for it.

The relation is WorkEffort <--- WorkEffortParty ---> Party. The code for the relation entity is below:

```typescript
@Model({db: {name: 'work_effort_parties'}})
export class WorkEffortParty extends BaseModel {
  @ManyToOne(
    () => WorkEffort,
    (workEffort: WorkEffort) => workEffort.parties,
    { unique: true }
  )
  workEffort!: WorkEffort;

  @ManyToOne(
    () => Party,
    (party: Party) => party.workEfforts,
    { unique: true }
  )
  party!: Party;

  @EnumField(
    'WorkEffortPartyRole',
    WorkEffortPartyRole,
  )
  role!: WorkEffortPartyRole;
}
```

I set both party and workEffort fields as unique but instead of a composite index I got two unique indices for each property alone.

Is there any way to indicate a composite index is wanted?

Thanks

**Comment by goldcaddy77** [comment]
@diegonc You'll want to use TypeORM composite indices like so: https://github.com/typeorm/typeorm/blob/master/docs/indices.md#indices-with-multiple-columns

**Comment by diegonc** [comment]
Thanks! It worked using `@Index`
