### ISSUE TITLE
Provide the description property for GraphQL schema purposes

### ISSUE THREAD

**Issue by metmirr** [goldcaddy77/warthog#348]
Type-graphql `Field` decorator accepts `description` option [Types and Fields](https://typegraphql.com/docs/types-and-fields.html). If we could add this option to warthog decorators that would be really useful.

```typescript
@Model()
class Recipe {
  @StringField({ description: "The title of the recipe" })
  title: string;
}
```

**Comment by goldcaddy77** [comment]
Work completed here: https://github.com/goldcaddy77/warthog/pull/349

The plan is to also have this represented as a `comment` in the Postgres schema, but it appears TypeORM's support for this isn't working>. I've filed an issue here: https://github.com/typeorm/typeorm/issues/5906 .  Will merge the schema part now and follow up on DB.

**Comment by metmirr** [comment]
Thank you! It is not possible to pass a description from the command line right? e.g `generate recipe title:string!:The-title-of-the-recipe`.

**Comment by goldcaddy77** [comment]
That’s correct. The syntax for the CLI generate command is already complex enough, so I’m not planning on adding advanced options. For advanced options, just generate your model and then make the necessary updates to the decorators in the model file.

**Comment by goldcaddy77** [comment]
Added in #349
