### ISSUE TITLE
asynchronous context

### ISSUE THREAD

**Issue by diegonc** [goldcaddy77/warthog#352]
Is it possible to use an async function or return a promise from the context function? For instance, to fetch data from the database when the JWT token doesn't provide all of the user information

**Comment by goldcaddy77** [comment]
Yes, this does support promises already: https://github.com/goldcaddy77/warthog/blob/master/src/core/server.ts#L229

**Comment by diegonc** [comment]
The readme says object and I wasn't sure about promises. Thanks!
Should this be closed?

**Comment by goldcaddy77** [comment]
Let’s leave it open until I update the docs. Or feel free to toss in a quick docs PR.

**Comment by diegonc** [comment]
Sorry to bring this topic back. But is it possible to inject services to be used inside the context function?

**Comment by goldcaddy77** [comment]
This is not possible - what are you trying to do?

**Comment by diegonc** [comment]
> This is not possible though DI. The solution you came up with is the preferred way. Did you want to look up the user or something?

Yes! The token only carries an ID so I need to lookup the rest of the user
