### ISSUE TITLE
Inject service for other model

### ISSUE THREAD

**Issue by diegonc** [goldcaddy77/warthog#353]
I'm following the transaction example and I need to do something a bit more complex.
My models are:

```
WorkEffort <-> WorkEffortParty <-> Party
```
So, when I create a `WorkEffort` I want to associate it with two parties so I need the service for `WorkEffortParty` to be called from the `WorkEffort` service.

I already injected the repositories for Party so I can find the ones which will be linked.
But I can't figure out how to inject the `WorkEffortParty` service to create the links.

**Comment by diegonc** [comment]
Ok, I managed to do it using the TransactionManager injected to my service, like below:

```
const wepClient = manager?.create('WorkEffortParty', {
      workEffort: workEffortRes,
      party: client,
      role: WorkEffortPartyRole.WeprClient,
      createdById: userId
    })
manager?.save(wepClient, {reload: true})
```

But I wonder if it's better to get an instance of the `BaseService` somehow

**Comment by goldcaddy77** [comment]
Have a look at the Feature Flag example.  `FeatureFlagUser` is similar to what you're trying to do: https://github.com/goldcaddy77/warthog/tree/master/examples/07-feature-flags/src/feature-flag-user

**Comment by diegonc** [comment]
It looks more straightforward than what a I came up with the manager instance. I'll give a try, thanks!
