### ISSUE TITLE
Vulnerability in "class-transformer" package

### ISSUE THREAD

**Issue by FOSSforlife** [goldcaddy77/warthog#356]
This showed up in my GitHub repo, and it looks like it's coming from Warthog's dependencies:

![Screenshot from 2020-04-26 15-24-55](https://user-images.githubusercontent.com/22383534/80321494-4d6b9700-87d2-11ea-85a8-8221b7726acb.png)

I did a quick search through warthog's code and it doesn't seem like the package is being used anywhere.

**Comment by goldcaddy77** [comment]
This is pretty common in the npm ecosystem. I’ll stay on top of this as much as I can but note that you can explicitly require this version in your code (ie `yarn add class-transformer@latest`).
