### ISSUE TITLE
Make pluralization optional for table names

### ISSUE THREAD

**Issue by metmirr** [goldcaddy77/warthog#359]
I can see that by default pluralization is on for table names https://github.com/goldcaddy77/warthog/pull/16. Can we make it optional?

We use warthog as our GraphQL API framework and there is another project that we generate `typeorm` models from the warthog database. So the problem here is entity names they end with `s` and which is really confusing for us.

**Comment by goldcaddy77** [comment]
Yes, you should be able to override the default TypeORM naming strategy by passing it into `dbOptions`: https://github.com/goldcaddy77/warthog/blob/2cbc1a11b1668347fab6255e29a50049eede81ea/src/core/server.ts#L66

You’ll just need to extend this and update `tableName`: https://github.com/goldcaddy77/warthog/blob/master/src/torm/SnakeNamingStrategy.ts

**Comment by metmirr** [comment]
Thanks! It works well but when I generate models with `warthog generate` command it add `s` and when I run migrations command table is created with `s`. And then I run development server with sync option true, I end up having two tables.

**Comment by metmirr** [comment]
Leaving this here in case someone else needs:

```ts
import { SnakeNamingStrategy } from 'warthog';

class CustomNamingStrategy extends SnakeNamingStrategy {
  constructor() {
    super();
  }
  tableName(className: string, customName?: string): string {
    return customName ? customName : `${snakeCase(className)}`;
  }
}

// index.ts
const server = getServer({}, { namingStrategy: new CustomNamingStrategy() });
```

**Comment by goldcaddy77** [comment]
Thanks for documenting the workaround
