### ISSUE TITLE
Adding constructor to BaseModel

### ISSUE THREAD

**Issue by metmirr** [goldcaddy77/warthog#362]
**Do you want to request a _feature_ or report a _bug_?**

Feature

It would be good if `BaseModel` has a constructor with an optional parameter. Something like this maybe:

```typescript
@Model()
class User extends BaseModel {
  @StringField()
  username!: string

  constructor(init?: Partial<User>) {
    super();
    Object.assign(this, init);
  }
}
```

**Comment by goldcaddy77** [comment]
What are you trying to do exactly?

**Comment by goldcaddy77** [comment]
A Warthog Model is a TypeORM entity, so you can use the entity manager API to create new records: https://github.com/typeorm/typeorm/blob/master/docs/entity-manager-api.md

**Comment by metmirr** [comment]
I want to create a new instance of my model like this:
```ts
const user = new User({ username: 'joe' })
```

Not like this:
```ts
const user = new User()
user.username = 'joe'
```

**Comment by goldcaddy77** [comment]
I’d recommend using BaseService to create your records, as it layers in validation for free:

https://github.com/goldcaddy77/warthog/blob/master/src/core/BaseService.ts#L182

If you don’t want to use BaseService, I’d recommend using the TypeORM repository or entity manager to create them (basically what I do in BaseService.

Is there something you can’t achieve with either of those?

**Comment by metmirr** [comment]
Thank you for your quick response!

Okay, here is what I do:

- We have a warthog project. And for some reason, we want the users to run only `queries`(not `mutations`)
- Another project that updates the warthog database. Here we use warthog models(from warthog project) and typeorm entity manager. So here we want to allows other developers to run database queries but these queries are limited to `save`, `update`, `remove`. It is a nice feature we want to have since we can generate database models easily:

```ts
import { User } from '..path/to/warthog-project'

function handleNewUser(db: DB) {
  const user = new User({ username: 'joe' })
  db.save(user)
  
}
```

**Comment by goldcaddy77** [comment]
Do you want to secure the app so that the readonly users are truly not authorized to do creates, updates and deletes?

If so, I’d recommend you have them use the APIs directly and use authorization rules to lock them out.

If you’re not super concerned about that and you can share code, why not create a UserReadonly service that just exposes the `find` and `fineOne` methods?

Still not sure how your situation leads to wanting a constructor on BaseModel.

**Comment by goldcaddy77** [comment]
Happy to chat in person (Zoom) if this doesn’t make sense.

**Comment by metmirr** [comment]
That would be so good actually! Are you on Keybase?

**Comment by goldcaddy77** [comment]
Update: we Zoomed and @metmirr can actually use the Warthog services (that extend from BaseService) directly. The trick here is that he’s not running a `Server` in that project, so he just needs to instantiate the `Config’ service to pull in the necessary environment variables and spin up a TypeORM connection and will be all set.
