### ISSUE TITLE
Application runtime env vars required to compile

### ISSUE THREAD

**Issue by mknapik** [goldcaddy77/warthog#363]
I was working on distributing warthog app as a container image and stumbled upon a problem.
Usually, when working with containers I package compiled version of an app and treat image as an artifact. This way, once I test it on dev environment, I can promote (retag) image to qa, and then to production environment. Therefore app configuration cannot be known upfront when compiling a source code.

Here is an example Dockerfile using `warthog` project.

```Dockerfile
FROM node:12-alpine

WORKDIR /code

EXPOSE 4100

COPY package.json /code
COPY yarn.lock /code
RUN yarn install --frozen-lockfile && yarn cache clean

COPY . /code
RUN yarn run codegen && yarn run compile

CMD ["node", "dist/src/index.js"]
```
Running `docker build .` results in errors such as:
`Error: Config: WARTHOG_APP_HOST is required: undefined`
`Error: Config: WARTHOG_DB_HOST is required: undefined`

Are those env vars really necessary to generate typeorm/graphql boilerplate code?
Does it use DB connection to infer data schema?

**Comment by mknapik** [comment]
I focused on wrong vars. Setting `NODE_ENV` helped.

```Dockerfile
FROM node:12-alpine

WORKDIR /code

EXPOSE 4100

COPY package.json /code
COPY yarn.lock /code
RUN yarn install --frozen-lockfile && yarn cache clean

COPY . /code

ENV NODE_ENV=development
RUN yarn run codegen && yarn run compile
ENV NODE_ENV ""

CMD ["node", "dist/src/index.js"]
```

Sorry for noise and keep up the good work!

**Comment by goldcaddy77** [comment]
Sweet, glad you figured it out.  Would love to see a PR into [warthog-starter](https://github.com/goldcaddy77/warthog-starter) if you have a solid Docker setup that you're using with Warthog.  Is your project open or closed source?

**Comment by mknapik** [comment]
I had to give up on using warthog because of non-functional requirements.

I ended up with the following Dockerfile:

```
FROM node:12-alpine AS base

RUN apk add --no-cache --update --quiet dumb-init=~1
WORKDIR /code
EXPOSE 4100
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

ENV WARTHOG_AUTO_GENERATE_FILES=false

FROM base AS development

COPY package.json /code
COPY yarn.lock /code
RUN yarn install --frozen-lockfile && yarn cache clean

COPY . /code

RUN NODE_ENV=development yarn run codegen && yarn run compile

CMD ["yarn", "start:dev"]

FROM base AS production

ENV WARTHOG_DB_ENTITIES=dist/src/**/*.model.js
ENV WARTHOG_DB_MIGRATIONS=dist/db/migrations/**/*.js
ENV WARTHOG_DB_SUBSCRIBERS=dist/src/**/*.model.js
ENV WARTHOG_RESOLVERS_PATH=dist/src/**/*.resolver.js

COPY package.json /code
COPY yarn.lock /code
RUN yarn install --production --frozen-lockfile && yarn cache clean

COPY --from=development /code/dist /code/dist
COPY --from=development /code/generated /code/generated
COPY --from=development /code/warthog.config.js /code/

CMD ["yarn", "start"]
```

It's a multi stage build; `development` stage can be used in docker compose for local development. `production` stage copies compiled files from `development` stage and has significantly smaller size due to skipping development dependencies.
