### ISSUE TITLE
How do I define an apiOnly model?

### ISSUE THREAD

**Issue by diegonc** [goldcaddy77/warthog#369]
Hi, I want to define a model that is exposed to the api side of warthog but which is not present in the database.

I tried using @ObjectType() annotation only in my model class but warthog doesn't generates the auxiliary types required by the resolver like `${className}WhereArgs`.

Any ideas?

**Comment by goldcaddy77** [comment]
See https://github.com/goldcaddy77/warthog/blob/main/README.md#api-only

**Comment by diegonc** [comment]
Yeah I saw that. But it’s only for a field. I need the entire entity to be out of the main database

**Comment by goldcaddy77** [comment]
Interesting. What is the use case? This is not currently supported, but I could add this pretty easily by allowing you to specify `{ db: false }` in the `Model` options:

https://github.com/goldcaddy77/warthog/blob/main/src/decorators/Model.ts#L32

**Comment by goldcaddy77** [comment]
Done: https://github.com/goldcaddy77/warthog/pull/370.

**Comment by goldcaddy77** [comment]
Reopening so that I remember to add documentation

**Comment by diegonc** [comment]
> Interesting. What is the use case? 

My use case is having some entities load from a secondary database like the filesystem
