### ISSUE TITLE
Need Logo

### ISSUE THREAD

**Issue by goldcaddy77** [goldcaddy77/warthog#4]

**Comment by richardbmx** [comment]
@goldcaddy77  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by goldcaddy77** [comment]
Hi Richard. I'd ❤️that. I was initially thinking something similar to the [Night Shift Owl](static1.squarespace.com/static/57ed18381b631b4217bef4b9/t/5829fbc929687f3584759099/1479146442986/NSB+Logo.jpg?format=1500w), but a Warthog, but open to check out whatever you come up with, too. Thanks!

**Comment by richardbmx** [comment]
@goldcaddy77 the link you have put does not work if you can load it again it would be great

**Comment by goldcaddy77** [comment]
Link updated!  If you'd like to chat more synchronously, you can find me in gitter - 
https://gitter.im/warthog-graphql/community

**Comment by goldcaddy77** [comment]
@richardbmx - did you end up coming up with anything?

**Comment by richardbmx** [comment]
@goldcaddy77  Greetings, sorry the delay I did not receive the notifications of your answer, I will work on the logo and in brebe I will send you some ideas

**Comment by goldcaddy77** [comment]
@richardbmx Sounds good 👍

**Comment by richardbmx** [comment]
@goldcaddy77  I present my proposal developed in the idea that you pose of the Warthog in a very minimalist and unique way that works very well in different colors and sizes, I hope you like it, if you want any change you just have to ask me what I can do with pleasure

![logo127](https://user-images.githubusercontent.com/35604837/54549735-0a10e900-4981-11e9-840a-e5bc18d516d9.png)

**Comment by goldcaddy77** [comment]
Wow, this is amazing!  Thanks for putting this together!!  A few things if you're down to riff on this a bit:

1. Is there a way to integrate the GraphQL logo somehow? (see below - pattern, not color)
2. Do you have any other font options you tried and liked?
3. The warthog looks totally badass - did you try a less viscious-looking version at all?  I had originally envisioned a more approachable-looking warthog, but this guy is very cool too. :)

<img width="200" alt="Screen Shot 2019-03-20 at 11 05 02 PM" src="https://user-images.githubusercontent.com/573625/54731473-c2e34d80-4b64-11e9-9c66-b58ef34ee8ba.png">

**Comment by richardbmx** [comment]
@goldcaddy77  Hello happy day ... I want to show you this variant that I have made focused on the changes that you suggest, I have used a slightly more straight text that gives more solids to the design and I have inserted in a simple way the GraphQL logo. I hope you like it if you want some change you just have to ask for it .. regards....

![logo127VARIANTE2](https://user-images.githubusercontent.com/35604837/55330032-09d31c00-545e-11e9-9bc3-23dbe223665e.png)

**Comment by goldcaddy77** [comment]
Wow @richardbmx this is amazing... thanks again! I'd love to put this one in the README:

![6BF30011-BB87-40DD-8488-91F427516261](https://user-images.githubusercontent.com/573625/55339814-06915d80-5469-11e9-9482-e05ca0863f18.jpeg)

Do you want to shoot me high-res files? Should we use PNG or does a different format make more sense?

**Comment by goldcaddy77** [comment]
Actually, if you want to contribute by adding a PR putting the images in a top-level `images` folder, that works too.

**Comment by richardbmx** [comment]
@goldcaddy77  Perfect I will generate the PR and additional to that I will make a google folder with all the necessary files to use or edit the design in the future, when I have everything ready I will mount the link of the folder here.

**Comment by goldcaddy77** [comment]
Excellent, thanks!!!

**Comment by richardbmx** [comment]
@goldcaddy77  All the editable files in the google folder together with a file that makes delivery to the copyright for its free use.. Thank you very much for allowing me to work on your project, I am available for future projects if you wish

[Google Drive](https://drive.google.com/open?id=13V_F5l-IIt6BDjlvpcwvMzwMZUHtycAh)

**Comment by goldcaddy77** [comment]
@richardbmx - would it be possible to get:

- Scalable graphic by itself (both in color and also a vector scalable version that could be colored (svg or png)
- A copy of the graphic + font like you've already provided, but with little or no white padding around the outside.  The white padding is making it difficult to get the right size on mobile (see below)

Thanks again - a bunch of my friends have been saying how badass the logo is :)

<img width="365" alt="Screen Shot 2019-04-21 at 8 28 42 PM" src="https://user-images.githubusercontent.com/573625/56477491-26b6aa00-6474-11e9-9eaf-550e5101542a.png">

**Comment by richardbmx** [comment]
@goldcaddy77  Above I have left you a folder of google drive with all the editable files in SVG. AI. PDF

**Comment by goldcaddy77** [comment]
Ohhhh right.  Thanks!  Closing :)
