### ISSUE TITLE
Allow custom PubSubEngine for GraphQL PubSub

### ISSUE THREAD

**Issue by dzhelezov** [goldcaddy77/warthog#422]
By default ApolloServer uses an EventEmitter-based PubSubEngine, and in general it is recommended to use a more scalable (like Redis-based) one. However, it doesn't seem to be possible to provide a custom implementation since as the`pubSub` implementation should be passed to the `buildSchema` call here : https://github.com/goldcaddy77/warthog/blob/b4649819be8b9af1627f2261532fcae6140246a2/src/core/server.ts#L161

Here's a relevant example from `type-graphql`:
https://github.com/MichalLytek/type-graphql/blob/d5e3403f7610ce8f53b919a3dd490806685570c7/examples/redis-subscriptions/index.ts#L27

**Comment by goldcaddy77** [comment]
Good call. Will take a crack at it this week.

**Comment by metmirr** [comment]
@goldcaddy77 what is the status of this issue? Isn't implemented right?

**Comment by goldcaddy77** [comment]
Hi @metmirr , this is not implemented yet.  If you want to put in a PR I'm happy to review and get it integrated.

**Comment by goldcaddy77** [comment]
This has been implemented.  See https://github.com/goldcaddy77/warthog/blob/main/src/core/server.ts#L185
