### ISSUE TITLE
Fetching typed json fields

### ISSUE THREAD

**Issue by metmirr** [goldcaddy77/warthog#464]
Resolvers don't fetch typed json fields when a resolver function has the `@Fields` parameter.  The example below is taken from examples/02:

```typescript
  @Query(() => [User])
  async users(
    @Args() { where, orderBy, limit, offset }: UserWhereArgs,
    @Fields() fields: string[]
  ): Promise<User[]> {}
```

![image](https://user-images.githubusercontent.com/11671753/121245406-4998b800-c8a0-11eb-8947-cb4cd23f9b90.png)

**Comment by goldcaddy77** [comment]
@metmirr Are you sure that record has a value in the DB?

**Comment by metmirr** [comment]
Yes, I am. Resolver without `@Fields` returns this data:
![image](https://user-images.githubusercontent.com/11671753/121771743-9961d280-cb71-11eb-8c6c-eb6b9bad7f4f.png)

**Comment by goldcaddy77** [comment]
Fixed in https://github.com/goldcaddy77/warthog/pull/467

**Comment by goldcaddy77** [comment]
Note that I needed to update the behavior of the `Fields` decorator to include all top-level fields.  This will bring along both JSON fields as well as associations.  Then `BaseModel` makes sure all values passed into `find` are actually fields on the table.  This is technically a breaking change - but I'd argue the `Fields` decorator wasn't really working as designed anyway.  Do you think this is ok, or should I create a new decorator with the new behavior?

**Comment by goldcaddy77** [comment]
I've merged this.  Feel free to play around and let me know if you think anything needs to be tweaked.

**Comment by metmirr** [comment]
> Note that I needed to update the behavior of the `Fields` decorator to include all top-level fields. This will bring along both JSON fields as well as associations. Then `BaseModel` makes sure all values passed into `find` are actually fields on the table. This is technically a breaking change - but I'd argue the `Fields` decorator wasn't really working as designed anyway. Do you think this is ok, or should I create a new decorator with the new behavior?

I think this is it, the decorator is working as expected with jsons, relations etc.

**Comment by metmirr** [comment]
> I've merged this. Feel free to play around and let me know if you think anything needs to be tweaked.

Working perfectly as expected, thank you so much! Really appreciated!
