### ISSUE TITLE
Filtering typed json fields

### ISSUE THREAD

**Issue by metmirr** [goldcaddy77/warthog#466]
Here https://github.com/goldcaddy77/warthog/pull/412 it is assumed filtering would work. There are some issues with generated classes and schema when `filter: true` is provided. Look at the `warthog/examples/02` and change `filter` to true:

```ts
@JSONField({ filter: true, nullable: true, gqlFieldType: EventObject })
typedJsonField?: EventObject;
```

In the `generated/classes.ts` there will a graphql field definition like this

```ts
@TypeGraphQLField(() => EventObject, { nullable: true })
typedJsonField_json?: JsonObject;
```

Since the filtering is enabled the graphql field and typescript type should be `EventObjectWhereInput` like this:

```ts
@TypeGraphQLField(() => EventObjectWhereInput, { nullable: true })
typedJsonField_json?: EventObjectWhereInput;
```

Also, one more important note when filtering is enabled the JSON objects should use warthog decorators instead of the type-graphql `Field` decorator. If not then the `*WhereInput` will not be generated for the object.

**Comment by goldcaddy77** [comment]
@metmirr  Thanks for logging the issue. Will take a look at it tonight.

**Comment by goldcaddy77** [comment]
Fixed in https://github.com/goldcaddy77/warthog/pull/467

**Comment by goldcaddy77** [comment]
@metmirr since the filtering mechanism in `BaseService` will query an arbitrary depth, it probably doesn't make sense to type the `WhereInput`, right?  Check out [the PR](https://github.com/goldcaddy77/warthog/pull/467).  The create/update inputs and the returned objects are typed, but the filtering isn't.  Does this make sense?

**Comment by metmirr** [comment]
Yeah, make sense to keep where input as json.
Works as expected! Thanks very much!
