### ISSUE TITLE
@Unique loses Enum type in generated code

### ISSUE THREAD

**Issue by deweyjose** [goldcaddy77/warthog#56]
Try to use @Unique on a model. If a field specified in the Unique set is an enum the type is lost in the generated code.

// model
@Model()
@Unique(["name", "type"])
export class FormElement extends BaseModel {
    @StringField({ maxLength: 50 })
    name?: string;

    @EnumField('FormElementType', FormElementType, { nullable: true })
    type?: FormElementType;

    @OneToMany(() => FormFormElement, (formFormElement: FormFormElement) => formFormElement.formElement)
    formFormElements?: FormFormElement[];
}

// generated 
@TypeGraphQLInputType()
export class FormElementWhereUniqueInput {
  @TypeGraphQLField(type => String, { nullable: true })
  id?: string;

  @TypeGraphQLField(type => String, { nullable: true })
  name?: string;

  @TypeGraphQLField(type => undefined, { nullable: true })
  type?: string;
}

**Comment by goldcaddy77** [comment]
@deweyjose are you just trying to make one of the fields unique or do you want the uniqueness to be on the pair of fields?

**Comment by deweyjose** [comment]
uniqueness across the set of fields

**Comment by goldcaddy77** [comment]
@deweyjose can we close this now?

**Comment by deweyjose** [comment]
looks good, thank you
