### ISSUE TITLE
prereq typo

### ISSUE THREAD

**Issue by 7KAG7** [goldcaddy77/warthog#58]
If you're on OSX have have Homebrew installed, you can simply run:

should read

If you're on OSX and have Homebrew installed, you can simply run:

**Comment by goldcaddy77** [comment]
Sweet, want to fork and put in a PR?

**Comment by 7KAG7** [comment]
just added a PR, but went from a the master to the README.md, not sure if had that right. I also, like you said, should have put more details into the description. Even though it was simple I'm guessing folks like to know the detail. Let me know if you want me to do it over.

**Comment by goldcaddy77** [comment]
Hey, typically you'd just have a PR message here - everything else looks
great. It's aimed at my master branch... Which is correct.

Nice work guern!

**Comment by goldcaddy77** [comment]
Closing per 
https://github.com/goldcaddy77/warthog/pull/59
