### ISSUE TITLE
sh: yarn: command not found

### ISSUE THREAD

**Issue by 7KAG7** [goldcaddy77/warthog#60]
on npm start I get the following:

K-MacBook-Pro:~ k$ cd warthog-starter
K-MacBook-Pro:warthog-starter k$ npm start

> warthog-example@0.0.0 start /Users/k/warthog-starter
> DEBUG=warthog* yarn start:ts

sh: yarn: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! warthog-example@0.0.0 start: `DEBUG=warthog* yarn start:ts`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the warthog-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/k/.npm/_logs/2019-03-12T19_00_53_761Z-debug.log

**Comment by goldcaddy77** [comment]
The project assumes you're using yarn.

Run `npm i -g yarn@latest`
