### ISSUE TITLE
add support for JSON fields

### ISSUE THREAD

**Issue by deweyjose** [goldcaddy77/warthog#85]
https://github.com/taion/graphql-type-json

**Comment by goldcaddy77** [comment]
Thanks @deweyjose - will look into this.

**Comment by deweyjose** [comment]
I think I was able to address it in this branch https://github.com/goldcaddy77/warthog/tree/support_json_type

**Comment by goldcaddy77** [comment]
Closing https://github.com/goldcaddy77/warthog/pull/86
