### ISSUE TITLE
TypeError: Class constructor BaseModel cannot be invoked without 'new'

### ISSUE THREAD

**Issue by bdombro** [goldcaddy77/warthog#90]
I'm trying to impliment a basic example of migrations at https://github.com/bdombro/warthog-migration-example.

When running `ts-node tools/seed.ts`, or `ts-node-dev --type-check src/index.ts`, I get the following error and do not know how to fix.

`TypeError: Class constructor BaseModel cannot be invoked without 'new'`

I think it's a core issue.

**Comment by bdombro** [comment]
Nevermind, i figured out the issue was with the tsconfig target. I borrowed the tsconfig from your starter, but realize now it's incompatible with latest

**Comment by goldcaddy77** [comment]
Ahhh nice catch.
